# Generated by Django 5.2.15 on 2026-06-26 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="name_de",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="service",
            name="name_en",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="service",
            name="name_es",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="service",
            name="name_fr",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="service",
            name="name_it",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="service",
            name="name_ja",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="service",
            name="name_nl",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="service",
            name="name_ru",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="service",
            name="name_zh_hans",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="service",
            name="name_zh_hant",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="service",
            name="p1_de",
            field=models.TextField(
                blank=True, max_length=5000, null=True, verbose_name="(1) Paragraph"
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="p1_en",
            field=models.TextField(
                blank=True, max_length=5000, null=True, verbose_name="(1) Paragraph"
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="p1_es",
            field=models.TextField(
                blank=True, max_length=5000, null=True, verbose_name="(1) Paragraph"
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="p1_fr",
            field=models.TextField(
                blank=True, max_length=5000, null=True, verbose_name="(1) Paragraph"
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="p1_it",
            field=models.TextField(
                blank=True, max_length=5000, null=True, verbose_name="(1) Paragraph"
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="p1_ja",
            field=models.TextField(
                blank=True, max_length=5000, null=True, verbose_name="(1) Paragraph"
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="p1_nl",
            field=models.TextField(
                blank=True, max_length=5000, null=True, verbose_name="(1) Paragraph"
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="p1_ru",
            field=models.TextField(
                blank=True, max_length=5000, null=True, verbose_name="(1) Paragraph"
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="p1_title_de",
            field=models.CharField(
                blank=True,
                max_length=200,
                null=True,
                verbose_name="(1) Paragraph's Title",
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="p1_title_en",
            field=models.CharField(
                blank=True,
                max_length=200,
                null=True,
                verbose_name="(1) Paragraph's Title",
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="p1_title_es",
            field=models.CharField(
                blank=True,
                max_length=200,
                null=True,
                verbose_name="(1) Paragraph's Title",
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="p1_title_fr",
            field=models.CharField(
                blank=True,
                max_length=200,
                null=True,
                verbose_name="(1) Paragraph's Title",
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="p1_title_it",
            field=models.CharField(
                blank=True,
                max_length=200,
                null=True,
                verbose_name="(1) Paragraph's Title",
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="p1_title_ja",
            field=models.CharField(
                blank=True,
                max_length=200,
                null=True,
                verbose_name="(1) Paragraph's Title",
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="p1_title_nl",
            field=models.CharField(
                blank=True,
                max_length=200,
                null=True,
                verbose_name="(1) Paragraph's Title",
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="p1_title_ru",
            field=models.CharField(
                blank=True,
                max_length=200,
                null=True,
                verbose_name="(1) Paragraph's Title",
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="p1_title_zh_hans",
            field=models.CharField(
                blank=True,
                max_length=200,
                null=True,
                verbose_name="(1) Paragraph's Title",
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="p1_title_zh_hant",
            field=models.CharField(
                blank=True,
                max_length=200,
                null=True,
                verbose_name="(1) Paragraph's Title",
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="p1_zh_hans",
            field=models.TextField(
                blank=True, max_length=5000, null=True, verbose_name="(1) Paragraph"
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="p1_zh_hant",
            field=models.TextField(
                blank=True, max_length=5000, null=True, verbose_name="(1) Paragraph"
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="p2_de",
            field=models.TextField(
                blank=True, max_length=5000, null=True, verbose_name="(2) Paragraph"
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="p2_en",
            field=models.TextField(
                blank=True, max_length=5000, null=True, verbose_name="(2) Paragraph"
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="p2_es",
            field=models.TextField(
                blank=True, max_length=5000, null=True, verbose_name="(2) Paragraph"
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="p2_fr",
            field=models.TextField(
                blank=True, max_length=5000, null=True, verbose_name="(2) Paragraph"
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="p2_it",
            field=models.TextField(
                blank=True, max_length=5000, null=True, verbose_name="(2) Paragraph"
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="p2_ja",
            field=models.TextField(
                blank=True, max_length=5000, null=True, verbose_name="(2) Paragraph"
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="p2_nl",
            field=models.TextField(
                blank=True, max_length=5000, null=True, verbose_name="(2) Paragraph"
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="p2_ru",
            field=models.TextField(
                blank=True, max_length=5000, null=True, verbose_name="(2) Paragraph"
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="p2_title_de",
            field=models.CharField(
                blank=True,
                max_length=200,
                null=True,
                verbose_name="(2) Paragraph's Title",
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="p2_title_en",
            field=models.CharField(
                blank=True,
                max_length=200,
                null=True,
                verbose_name="(2) Paragraph's Title",
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="p2_title_es",
            field=models.CharField(
                blank=True,
                max_length=200,
                null=True,
                verbose_name="(2) Paragraph's Title",
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="p2_title_fr",
            field=models.CharField(
                blank=True,
                max_length=200,
                null=True,
                verbose_name="(2) Paragraph's Title",
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="p2_title_it",
            field=models.CharField(
                blank=True,
                max_length=200,
                null=True,
                verbose_name="(2) Paragraph's Title",
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="p2_title_ja",
            field=models.CharField(
                blank=True,
                max_length=200,
                null=True,
                verbose_name="(2) Paragraph's Title",
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="p2_title_nl",
            field=models.CharField(
                blank=True,
                max_length=200,
                null=True,
                verbose_name="(2) Paragraph's Title",
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="p2_title_ru",
            field=models.CharField(
                blank=True,
                max_length=200,
                null=True,
                verbose_name="(2) Paragraph's Title",
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="p2_title_zh_hans",
            field=models.CharField(
                blank=True,
                max_length=200,
                null=True,
                verbose_name="(2) Paragraph's Title",
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="p2_title_zh_hant",
            field=models.CharField(
                blank=True,
                max_length=200,
                null=True,
                verbose_name="(2) Paragraph's Title",
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="p2_zh_hans",
            field=models.TextField(
                blank=True, max_length=5000, null=True, verbose_name="(2) Paragraph"
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="p2_zh_hant",
            field=models.TextField(
                blank=True, max_length=5000, null=True, verbose_name="(2) Paragraph"
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="p3_de",
            field=models.TextField(
                blank=True, max_length=5000, null=True, verbose_name="(3) Paragraph"
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="p3_en",
            field=models.TextField(
                blank=True, max_length=5000, null=True, verbose_name="(3) Paragraph"
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="p3_es",
            field=models.TextField(
                blank=True, max_length=5000, null=True, verbose_name="(3) Paragraph"
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="p3_fr",
            field=models.TextField(
                blank=True, max_length=5000, null=True, verbose_name="(3) Paragraph"
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="p3_it",
            field=models.TextField(
                blank=True, max_length=5000, null=True, verbose_name="(3) Paragraph"
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="p3_ja",
            field=models.TextField(
                blank=True, max_length=5000, null=True, verbose_name="(3) Paragraph"
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="p3_nl",
            field=models.TextField(
                blank=True, max_length=5000, null=True, verbose_name="(3) Paragraph"
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="p3_ru",
            field=models.TextField(
                blank=True, max_length=5000, null=True, verbose_name="(3) Paragraph"
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="p3_title_de",
            field=models.CharField(
                blank=True,
                max_length=200,
                null=True,
                verbose_name="(3) Paragraph's Title",
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="p3_title_en",
            field=models.CharField(
                blank=True,
                max_length=200,
                null=True,
                verbose_name="(3) Paragraph's Title",
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="p3_title_es",
            field=models.CharField(
                blank=True,
                max_length=200,
                null=True,
                verbose_name="(3) Paragraph's Title",
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="p3_title_fr",
            field=models.CharField(
                blank=True,
                max_length=200,
                null=True,
                verbose_name="(3) Paragraph's Title",
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="p3_title_it",
            field=models.CharField(
                blank=True,
                max_length=200,
                null=True,
                verbose_name="(3) Paragraph's Title",
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="p3_title_ja",
            field=models.CharField(
                blank=True,
                max_length=200,
                null=True,
                verbose_name="(3) Paragraph's Title",
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="p3_title_nl",
            field=models.CharField(
                blank=True,
                max_length=200,
                null=True,
                verbose_name="(3) Paragraph's Title",
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="p3_title_ru",
            field=models.CharField(
                blank=True,
                max_length=200,
                null=True,
                verbose_name="(3) Paragraph's Title",
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="p3_title_zh_hans",
            field=models.CharField(
                blank=True,
                max_length=200,
                null=True,
                verbose_name="(3) Paragraph's Title",
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="p3_title_zh_hant",
            field=models.CharField(
                blank=True,
                max_length=200,
                null=True,
                verbose_name="(3) Paragraph's Title",
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="p3_zh_hans",
            field=models.TextField(
                blank=True, max_length=5000, null=True, verbose_name="(3) Paragraph"
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="p3_zh_hant",
            field=models.TextField(
                blank=True, max_length=5000, null=True, verbose_name="(3) Paragraph"
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="short_description_de",
            field=models.TextField(
                blank=True, max_length=350, null=True, verbose_name="Short Description"
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="short_description_en",
            field=models.TextField(
                blank=True, max_length=350, null=True, verbose_name="Short Description"
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="short_description_es",
            field=models.TextField(
                blank=True, max_length=350, null=True, verbose_name="Short Description"
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="short_description_fr",
            field=models.TextField(
                blank=True, max_length=350, null=True, verbose_name="Short Description"
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="short_description_it",
            field=models.TextField(
                blank=True, max_length=350, null=True, verbose_name="Short Description"
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="short_description_ja",
            field=models.TextField(
                blank=True, max_length=350, null=True, verbose_name="Short Description"
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="short_description_nl",
            field=models.TextField(
                blank=True, max_length=350, null=True, verbose_name="Short Description"
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="short_description_ru",
            field=models.TextField(
                blank=True, max_length=350, null=True, verbose_name="Short Description"
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="short_description_zh_hans",
            field=models.TextField(
                blank=True, max_length=350, null=True, verbose_name="Short Description"
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="short_description_zh_hant",
            field=models.TextField(
                blank=True, max_length=350, null=True, verbose_name="Short Description"
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="slug_de",
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name="service",
            name="slug_en",
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name="service",
            name="slug_es",
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name="service",
            name="slug_fr",
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name="service",
            name="slug_it",
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name="service",
            name="slug_ja",
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name="service",
            name="slug_nl",
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name="service",
            name="slug_ru",
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name="service",
            name="slug_zh_hans",
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name="service",
            name="slug_zh_hant",
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name="servicecategory",
            name="description_de",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="servicecategory",
            name="description_en",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="servicecategory",
            name="description_es",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="servicecategory",
            name="description_fr",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="servicecategory",
            name="description_it",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="servicecategory",
            name="description_ja",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="servicecategory",
            name="description_nl",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="servicecategory",
            name="description_ru",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="servicecategory",
            name="description_zh_hans",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="servicecategory",
            name="description_zh_hant",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="servicecategory",
            name="name_de",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="servicecategory",
            name="name_en",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="servicecategory",
            name="name_es",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="servicecategory",
            name="name_fr",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="servicecategory",
            name="name_it",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="servicecategory",
            name="name_ja",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="servicecategory",
            name="name_nl",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="servicecategory",
            name="name_ru",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="servicecategory",
            name="name_zh_hans",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="servicecategory",
            name="name_zh_hant",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="servicecategory",
            name="slug_de",
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name="servicecategory",
            name="slug_en",
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name="servicecategory",
            name="slug_es",
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name="servicecategory",
            name="slug_fr",
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name="servicecategory",
            name="slug_it",
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name="servicecategory",
            name="slug_ja",
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name="servicecategory",
            name="slug_nl",
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name="servicecategory",
            name="slug_ru",
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name="servicecategory",
            name="slug_zh_hans",
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name="servicecategory",
            name="slug_zh_hant",
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name="serviceimage",
            name="description_de",
            field=models.CharField(
                blank=True, max_length=60, null=True, verbose_name="Description"
            ),
        ),
        migrations.AddField(
            model_name="serviceimage",
            name="description_en",
            field=models.CharField(
                blank=True, max_length=60, null=True, verbose_name="Description"
            ),
        ),
        migrations.AddField(
            model_name="serviceimage",
            name="description_es",
            field=models.CharField(
                blank=True, max_length=60, null=True, verbose_name="Description"
            ),
        ),
        migrations.AddField(
            model_name="serviceimage",
            name="description_fr",
            field=models.CharField(
                blank=True, max_length=60, null=True, verbose_name="Description"
            ),
        ),
        migrations.AddField(
            model_name="serviceimage",
            name="description_it",
            field=models.CharField(
                blank=True, max_length=60, null=True, verbose_name="Description"
            ),
        ),
        migrations.AddField(
            model_name="serviceimage",
            name="description_ja",
            field=models.CharField(
                blank=True, max_length=60, null=True, verbose_name="Description"
            ),
        ),
        migrations.AddField(
            model_name="serviceimage",
            name="description_nl",
            field=models.CharField(
                blank=True, max_length=60, null=True, verbose_name="Description"
            ),
        ),
        migrations.AddField(
            model_name="serviceimage",
            name="description_ru",
            field=models.CharField(
                blank=True, max_length=60, null=True, verbose_name="Description"
            ),
        ),
        migrations.AddField(
            model_name="serviceimage",
            name="description_zh_hans",
            field=models.CharField(
                blank=True, max_length=60, null=True, verbose_name="Description"
            ),
        ),
        migrations.AddField(
            model_name="serviceimage",
            name="description_zh_hant",
            field=models.CharField(
                blank=True, max_length=60, null=True, verbose_name="Description"
            ),
        ),
    ]
