[build-system]
requires = [
  "setuptools >= 77",
  "wheel",
]
build-backend = "setuptools.build_meta"

[project]
name = "django-service"
description = "Django application provide simple category/service details"
readme = "README.md"
authors = [
    { name = "DLRSP", email = "dlrsp.dev@gmail.com" },
]
requires-python = ">=3.10"
dynamic = ["dependencies", "version"]
license = "MIT"
license-files = ["LICENSE"]
keywords = [
    "django",
    "services",
]
classifiers = [
  "Development Status :: 4 - Beta",
  "Intended Audience :: Developers",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3 :: Only",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python :: 3.14",
  "Framework :: Django",
  "Framework :: Django :: 4.2",
  "Framework :: Django :: 5.2",
  "Environment :: Web Environment",
  "Operating System :: OS Independent",
  "Topic :: Internet :: WWW/HTTP",
  "Topic :: Internet :: WWW/HTTP :: Dynamic Content",
  "Topic :: Internet :: WWW/HTTP :: WSGI :: Application",
  "Topic :: Software Development :: Libraries :: Application Frameworks",
  "Topic :: Software Development :: Libraries",
]

[project.urls]
Homepage = "https://github.com/DLRSP/django-service"
Documentation = "https://dlrsp.github.io/django-service/"
Repository = "https://github.com/DLRSP/django-service"
Issues = "https://github.com/DLRSP/django-service/issues"
Changelog = "https://github.com/DLRSP/django-service/blob/main/CHANGELOG.rst"
Funding = "https://github.com/sponsors/DLRSP"

[project.optional-dependencies]
testing = [
  "coverage",
  "codecov",
  "pytest",
  "pytest-django",
]
linting = [
  "flake8",
  "flake8-pyproject",
  "flake8-bugbear",
  "flake8-comprehensions",
  "flake8-tidy-imports",
  "flake8-typing-imports",
  "pylint",
]

[tool.setuptools]
package-dir = { "" = "src" }
include-package-data = true
zip-safe = false

[tool.setuptools.dynamic]
dependencies = { file = "requirements/runtime.in" }
version = { attr = "services.__version__" }

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.data-files]
"share/django-service/requirements" = [
  "requirements/py310-django42.txt",
  "requirements/py310-django52.txt",
  "requirements/py311-django42.txt",
  "requirements/py311-django52.txt",
  "requirements/py312-django42.txt",
  "requirements/py312-django52.txt",
  "requirements/py313-django52.txt",
  "requirements/py314-django52.txt",
]

[tool.black]
target-version = ['py314']

[tool.isort]
profile = "black"

[tool.mypy]
check_untyped_defs = true
disallow_any_generics = true
disallow_incomplete_defs = true
disallow_untyped_defs = true
mypy_path = "src/"
no_implicit_optional = true
show_error_codes = true
warn_unreachable = true
warn_unused_ignores = true

[[tool.mypy.overrides]]
module = "tests.*"
allow_untyped_defs = true

[tool.pytest.ini_options]
addopts = """\
    --strict-config
    --strict-markers
    --ds=tests.settings
    """
django_find_project = false

[tool.coverage.paths]
source = ["src", ".tox/*/site-packages"]

[tool.coverage.run]
branch = true
source = ["services"]

[tool.coverage.report]
show_missing = true

[tool.flake8]
max-line-length = 120
exclude = [
    ".git",
    "__pycache__"
]
extend-ignore = [
    "E203","E501","W503"
]
count = true

[tool.towncrier]
package = "services"
package_dir = "src"
filename = "CHANGELOG.rst"
directory = "news/"
version = "0.3.2"
issue_format = "`#{issue} <https://github.com/DLRSP/django-service/issues/{issue}>`_"
type = [
  { name = "Process",                   directory = "process", showcontent = true },
  { name = "Deprecations and Removals", directory = "removal", showcontent = true },
  { name = "Features",                  directory = "feature", showcontent = true },
  { name = "Bug Fixes",                 directory = "bugfix",  showcontent = true },
  { name = "Vendored Libraries",        directory = "vendor",  showcontent = true },
  { name = "Improved Documentation",    directory = "doc",     showcontent = true },
  { name = "Trivial Changes",           directory = "trivial", showcontent = false },
]

[tool.bumpversion]
current_version = "0.3.2"
allow_dirty = true

[[tool.bumpversion.files]]
filename = "./src/services/__init__.py"
