[tox]
isolated_build = True
envlist =
    py{310,311}-django42

[testenv]
commands = python -W error::PendingDeprecationWarning -m coverage run --parallel -m pytest {posargs:tests}

[testenv:py310-django42]
deps =
    -rhttps://raw.githubusercontent.com/DLRSP/requirements/main/py310-dev.txt
    -rrequirements/py310-django42.txt

[testenv:py311-django42]
deps =
    -rhttps://raw.githubusercontent.com/DLRSP/requirements/main/py311-dev.txt
    -rrequirements/py311-django42.txt
